wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.5
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715780949
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.5
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
dropout:
  desc: null
  value: 0.9
gamma:
  desc: null
  value: 0.99
lr:
  desc: null
  value: 0.0001
method_name:
  desc: null
  value: spo+
neurons:
  desc: null
  value: 32
num_epochs:
  desc: null
  value: 10
