wandb_version: 1

lr:
  desc: null
  value: 0.001
gamma:
  desc: null
  value: 0.99
num_epochs:
  desc: null
  value: 30
neurons:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.7
method_name:
  desc: null
  value: spo+
val:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.5
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715868906
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.5
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
